/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   parametri__init
                     (Parametri         *message)
{
  static Parametri init_value = PARAMETRI__INIT;
  *message = init_value;
}
size_t parametri__get_packed_size
                     (const Parametri *message)
{
  assert(message->base.descriptor == &parametri__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t parametri__pack
                     (const Parametri *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &parametri__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t parametri__pack_to_buffer
                     (const Parametri *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &parametri__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Parametri *
       parametri__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Parametri *)
     protobuf_c_message_unpack (&parametri__descriptor,
                                allocator, len, data);
}
void   parametri__free_unpacked
                     (Parametri *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &parametri__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor parametri__field_descriptors[2] =
{
  {
    "mese",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Parametri, mese),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "anno",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Parametri, anno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned parametri__field_indices_by_name[] = {
  1,   /* field[1] = anno */
  0,   /* field[0] = mese */
};
static const ProtobufCIntRange parametri__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor parametri__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Parametri",
  "Parametri",
  "Parametri",
  "",
  sizeof(Parametri),
  2,
  parametri__field_descriptors,
  parametri__field_indices_by_name,
  1,  parametri__number_ranges,
  (ProtobufCMessageInit) parametri__init,
  NULL,NULL,NULL    /* reserved[123] */
};
